### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by banlon-jones** [banlon-jones/JavaScript-API-based-webapp#21]
Kanban board:
https://github.com/banlon-jones/JavaScript-API-based-webapp/projects/1

Dear reviewer the team is made up of 2 persons @banlon-jones  and @mprotic123

@banlon-jones representing student-A and 
@mprotic123 representing student-B

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @banlon-jones and @mprotic123,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
